// Code generated by scripts/gen-tla-instance-state-tests.py from formal/FireboltInstance.dot. DO NOT EDIT.
//
// Run `make formal-gen` to regenerate. The CI guard `make formal-verify` fails
// if this file is out of date relative to the TLA+ spec.

package controller

// tlaInstanceState is one reachable TLA+ state of the FireboltInstance spec,
// projected to the variables the instanceSim can materialise and observe.
type tlaInstanceState struct {
	Phase         string
	PostgresAvail bool
	MetadataAvail bool
	GatewayAvail  bool
}

// tlaInstanceTestCase pairs a TLA+ state with the set of states the model
// considers reachable from it via 0+ consecutive reconciler-only transitions.
// After instanceSim.Reconcile, the resulting state must lie in this closure.
type tlaInstanceTestCase struct {
	Start   tlaInstanceState
	Closure []tlaInstanceState // includes Start (stutter)
}


// 32 reachable states
var tlaInstanceStateCases = []tlaInstanceTestCase{
	{
		Start: tlaInstanceState{Phase: "degraded", PostgresAvail: false, MetadataAvail: false, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: false, MetadataAvail: false, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "degraded", PostgresAvail: false, MetadataAvail: false, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: false, MetadataAvail: false, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "degraded", PostgresAvail: false, MetadataAvail: true, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: false, MetadataAvail: true, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "degraded", PostgresAvail: false, MetadataAvail: true, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: false, MetadataAvail: true, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "degraded", PostgresAvail: true, MetadataAvail: false, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: true, MetadataAvail: false, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "degraded", PostgresAvail: true, MetadataAvail: false, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: true, MetadataAvail: false, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "degraded", PostgresAvail: true, MetadataAvail: true, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: true, MetadataAvail: true, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "degraded", PostgresAvail: true, MetadataAvail: true, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "ready", PostgresAvail: true, MetadataAvail: true, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "provisioning", PostgresAvail: false, MetadataAvail: false, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: false, MetadataAvail: false, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "provisioning", PostgresAvail: false, MetadataAvail: false, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: false, MetadataAvail: false, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "provisioning", PostgresAvail: false, MetadataAvail: true, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: false, MetadataAvail: true, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "provisioning", PostgresAvail: false, MetadataAvail: true, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: false, MetadataAvail: true, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "provisioning", PostgresAvail: true, MetadataAvail: false, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: true, MetadataAvail: false, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "provisioning", PostgresAvail: true, MetadataAvail: false, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: true, MetadataAvail: false, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "provisioning", PostgresAvail: true, MetadataAvail: true, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: true, MetadataAvail: true, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "provisioning", PostgresAvail: true, MetadataAvail: true, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "ready", PostgresAvail: true, MetadataAvail: true, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "ready", PostgresAvail: false, MetadataAvail: false, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: false, MetadataAvail: false, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "ready", PostgresAvail: false, MetadataAvail: false, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: false, MetadataAvail: false, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "ready", PostgresAvail: false, MetadataAvail: true, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: false, MetadataAvail: true, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "ready", PostgresAvail: false, MetadataAvail: true, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: false, MetadataAvail: true, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "ready", PostgresAvail: true, MetadataAvail: false, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: true, MetadataAvail: false, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "ready", PostgresAvail: true, MetadataAvail: false, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: true, MetadataAvail: false, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "ready", PostgresAvail: true, MetadataAvail: true, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "degraded", PostgresAvail: true, MetadataAvail: true, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "ready", PostgresAvail: true, MetadataAvail: true, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "ready", PostgresAvail: true, MetadataAvail: true, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "uninitialized", PostgresAvail: false, MetadataAvail: false, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: false, MetadataAvail: false, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "uninitialized", PostgresAvail: false, MetadataAvail: false, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: false, MetadataAvail: false, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "uninitialized", PostgresAvail: false, MetadataAvail: true, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: false, MetadataAvail: true, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "uninitialized", PostgresAvail: false, MetadataAvail: true, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: false, MetadataAvail: true, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "uninitialized", PostgresAvail: true, MetadataAvail: false, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: true, MetadataAvail: false, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "uninitialized", PostgresAvail: true, MetadataAvail: false, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: true, MetadataAvail: false, GatewayAvail: true},
		},
	},
	{
		Start: tlaInstanceState{Phase: "uninitialized", PostgresAvail: true, MetadataAvail: true, GatewayAvail: false},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: true, MetadataAvail: true, GatewayAvail: false},
		},
	},
	{
		Start: tlaInstanceState{Phase: "uninitialized", PostgresAvail: true, MetadataAvail: true, GatewayAvail: true},
		Closure: []tlaInstanceState{
			tlaInstanceState{Phase: "provisioning", PostgresAvail: true, MetadataAvail: true, GatewayAvail: true},
			tlaInstanceState{Phase: "ready", PostgresAvail: true, MetadataAvail: true, GatewayAvail: true},
		},
	},
}
