// Code generated by scripts/gen-tla-rotation-state-tests.py from formal/SigningKeyRotation.dot. DO NOT EDIT.
//
// Run `make formal-gen` to regenerate. The CI guard `make formal-verify` fails
// if this file is out of date relative to the TLA+ spec.

package controller

// tlaRotationKey is one signing key's modeled state, projected to what
// Status.Auth.SigningKeys can represent. Index in tlaRotationState.Keys is the
// kid number minus one.
//
// The model's "minting" phase projects to "absent": a key whose Certificate is
// applied but whose Secret is not ready yet is not in status and does not bump
// the generation counter, so nothing on the Go side distinguishes the two.
type tlaRotationKey struct {
	Phase      string
	Demoted    bool
	Anchored   bool
	RetainDone bool
}

// tlaRotationState is one reachable TLA+ state of SigningKeyRotation.tla.
// Field order is load-bearing: tlaRotationStatePool below uses positional
// composite literals, so changing these fields requires changing the
// generator's go_state_lit in lockstep.
type tlaRotationState struct {
	Keys      []tlaRotationKey
	Gen       int
	Converged bool
}

// tlaRotationTestCase references tlaRotationStatePool by index. Start is the
// starting state; Closure is the set of indices the model considers reachable
// from Start via 1+ reconciler-only transitions (plus Start itself when a
// stutter is legitimate).
type tlaRotationTestCase struct {
	Start   int
	Closure []int
}

// 19 unique reachable TLA+ states, projected.
var tlaRotationStatePool = []tlaRotationState{
	{[]tlaRotationKey{{"absent", false, false, false}, {"absent", false, false, false}, {"active", false, false, false}}, 2, true},
	{[]tlaRotationKey{{"absent", false, false, false}, {"active", false, false, false}, {"absent", false, false, false}}, 1, true},
	{[]tlaRotationKey{{"absent", false, false, false}, {"active", false, false, false}, {"validationOnly", false, false, false}}, 2, false},
	{[]tlaRotationKey{{"absent", false, false, false}, {"active", false, false, false}, {"validationOnly", false, false, false}}, 2, true},
	{[]tlaRotationKey{{"absent", false, false, false}, {"removing", true, true, true}, {"active", false, false, false}}, 2, false},
	{[]tlaRotationKey{{"absent", false, false, false}, {"removing", true, true, true}, {"active", false, false, false}}, 2, true},
	{[]tlaRotationKey{{"absent", false, false, false}, {"validationOnly", true, false, false}, {"active", false, false, false}}, 2, false},
	{[]tlaRotationKey{{"absent", false, false, false}, {"validationOnly", true, false, false}, {"active", false, false, false}}, 2, true},
	{[]tlaRotationKey{{"absent", false, false, false}, {"validationOnly", true, true, false}, {"active", false, false, false}}, 2, true},
	{[]tlaRotationKey{{"absent", false, false, false}, {"validationOnly", true, true, true}, {"active", false, false, false}}, 2, true},
	{[]tlaRotationKey{{"active", false, false, false}, {"absent", false, false, false}, {"absent", false, false, false}}, 0, true},
	{[]tlaRotationKey{{"active", false, false, false}, {"validationOnly", false, false, false}, {"absent", false, false, false}}, 1, false},
	{[]tlaRotationKey{{"active", false, false, false}, {"validationOnly", false, false, false}, {"absent", false, false, false}}, 1, true},
	{[]tlaRotationKey{{"removing", true, true, true}, {"active", false, false, false}, {"absent", false, false, false}}, 1, false},
	{[]tlaRotationKey{{"removing", true, true, true}, {"active", false, false, false}, {"absent", false, false, false}}, 1, true},
	{[]tlaRotationKey{{"validationOnly", true, false, false}, {"active", false, false, false}, {"absent", false, false, false}}, 1, false},
	{[]tlaRotationKey{{"validationOnly", true, false, false}, {"active", false, false, false}, {"absent", false, false, false}}, 1, true},
	{[]tlaRotationKey{{"validationOnly", true, true, false}, {"active", false, false, false}, {"absent", false, false, false}}, 1, true},
	{[]tlaRotationKey{{"validationOnly", true, true, true}, {"active", false, false, false}, {"absent", false, false, false}}, 1, true},
}

// 19 test cases referencing tlaRotationStatePool by index.
var tlaRotationStateCases = []tlaRotationTestCase{
	{0, []int{0}},
	{1, []int{1, 2}},
	{2, []int{2}},
	{3, []int{6}},
	{4, []int{4}},
	{5, []int{0}},
	{6, []int{6}},
	{7, []int{8}},
	{8, []int{8}},
	{9, []int{4}},
	{10, []int{10, 11}},
	{11, []int{11}},
	{12, []int{15}},
	{13, []int{13}},
	{14, []int{1, 2}},
	{15, []int{15}},
	{16, []int{17}},
	{17, []int{17}},
	{18, []int{13}},
}
