// Code generated by scripts/gen-tla-rotation-state-tests.py from formal/SigningKeyRotation.dot. DO NOT EDIT.
//
// Run `make formal-gen` to regenerate. The CI guard `make formal-verify` fails
// if this file is out of date relative to the TLA+ spec.

package controller

// tlaRotationObs is one engine's observed render: the key it signs with
// (Active) and the extra key it can validate (Other; 0 = none). It is the
// decomposed form of the engine's ObservedAuthHash.
type tlaRotationObs struct {
	Active int
	Other  int
}

// tlaRotationState is one reachable TLA+ state of the SigningKeyRotation
// spec, projected to the variables the rotation harness can materialise and
// observe. Field order is load-bearing: tlaRotationStatePool below uses
// positional composite literals; adding/reordering/removing fields here must
// be done in lockstep with the generator's go_state_lit.
type tlaRotationState struct {
	ActiveKey     int
	OtherKey      int // 0 = no non-Active key outstanding
	OtherState    string
	RotationDue   bool
	CertReady     bool
	RetainElapsed bool
	EngineObs     [2]tlaRotationObs // sorted by model engine name
}

// tlaRotationTestCase references tlaRotationStatePool by index. Start is the
// index of the starting state; Closure is the set of indices the model
// considers reachable from Start via 1+ reconciler-only transitions (plus
// Start itself when a stutter is legitimate). The indirection matches the
// engine and instance fixtures' shape.
type tlaRotationTestCase struct {
	Start   int
	Closure []int
}


// 37 unique reachable TLA+ states.
var tlaRotationStatePool = []tlaRotationState{
	{1, 0, "none", false, false, false, [2]tlaRotationObs{{1, 0}, {1, 0}}},
	{1, 0, "none", true, false, false, [2]tlaRotationObs{{1, 0}, {1, 0}}},
	{1, 2, "minting", true, false, false, [2]tlaRotationObs{{1, 0}, {1, 0}}},
	{1, 2, "minting", true, true, false, [2]tlaRotationObs{{1, 0}, {1, 0}}},
	{1, 2, "pending", true, true, false, [2]tlaRotationObs{{1, 0}, {1, 0}}},
	{1, 2, "pending", true, true, false, [2]tlaRotationObs{{1, 0}, {1, 2}}},
	{1, 2, "pending", true, true, false, [2]tlaRotationObs{{1, 2}, {1, 0}}},
	{1, 2, "pending", true, true, false, [2]tlaRotationObs{{1, 2}, {1, 2}}},
	{2, 0, "none", false, false, false, [2]tlaRotationObs{{2, 0}, {2, 0}}},
	{2, 0, "none", true, false, false, [2]tlaRotationObs{{2, 0}, {2, 0}}},
	{2, 1, "demoted", false, true, false, [2]tlaRotationObs{{1, 2}, {1, 2}}},
	{2, 1, "demoted", false, true, false, [2]tlaRotationObs{{1, 2}, {2, 1}}},
	{2, 1, "demoted", false, true, false, [2]tlaRotationObs{{2, 1}, {1, 2}}},
	{2, 1, "demoted", false, true, false, [2]tlaRotationObs{{2, 1}, {2, 1}}},
	{2, 1, "removing", false, true, true, [2]tlaRotationObs{{2, 0}, {2, 0}}},
	{2, 1, "removing", false, true, true, [2]tlaRotationObs{{2, 0}, {2, 1}}},
	{2, 1, "removing", false, true, true, [2]tlaRotationObs{{2, 1}, {2, 0}}},
	{2, 1, "removing", false, true, true, [2]tlaRotationObs{{2, 1}, {2, 1}}},
	{2, 1, "retiring", false, true, false, [2]tlaRotationObs{{2, 1}, {2, 1}}},
	{2, 1, "retiring", false, true, true, [2]tlaRotationObs{{2, 1}, {2, 1}}},
	{2, 3, "minting", true, false, false, [2]tlaRotationObs{{2, 0}, {2, 0}}},
	{2, 3, "minting", true, true, false, [2]tlaRotationObs{{2, 0}, {2, 0}}},
	{2, 3, "pending", true, true, false, [2]tlaRotationObs{{2, 0}, {2, 0}}},
	{2, 3, "pending", true, true, false, [2]tlaRotationObs{{2, 0}, {2, 3}}},
	{2, 3, "pending", true, true, false, [2]tlaRotationObs{{2, 3}, {2, 0}}},
	{2, 3, "pending", true, true, false, [2]tlaRotationObs{{2, 3}, {2, 3}}},
	{3, 0, "none", false, false, false, [2]tlaRotationObs{{3, 0}, {3, 0}}},
	{3, 2, "demoted", false, true, false, [2]tlaRotationObs{{2, 3}, {2, 3}}},
	{3, 2, "demoted", false, true, false, [2]tlaRotationObs{{2, 3}, {3, 2}}},
	{3, 2, "demoted", false, true, false, [2]tlaRotationObs{{3, 2}, {2, 3}}},
	{3, 2, "demoted", false, true, false, [2]tlaRotationObs{{3, 2}, {3, 2}}},
	{3, 2, "removing", false, true, true, [2]tlaRotationObs{{3, 0}, {3, 0}}},
	{3, 2, "removing", false, true, true, [2]tlaRotationObs{{3, 0}, {3, 2}}},
	{3, 2, "removing", false, true, true, [2]tlaRotationObs{{3, 2}, {3, 0}}},
	{3, 2, "removing", false, true, true, [2]tlaRotationObs{{3, 2}, {3, 2}}},
	{3, 2, "retiring", false, true, false, [2]tlaRotationObs{{3, 2}, {3, 2}}},
	{3, 2, "retiring", false, true, true, [2]tlaRotationObs{{3, 2}, {3, 2}}},
}

// 37 test cases referencing tlaRotationStatePool by index.
var tlaRotationStateCases = []tlaRotationTestCase{
	{0, []int{0}},
	{1, []int{2}},
	{2, []int{2}},
	{3, []int{4}},
	{4, []int{4}},
	{5, []int{5}},
	{6, []int{6}},
	{7, []int{10}},
	{8, []int{8}},
	{9, []int{20}},
	{10, []int{10}},
	{11, []int{11}},
	{12, []int{12}},
	{13, []int{18}},
	{14, []int{8}},
	{15, []int{15}},
	{16, []int{16}},
	{17, []int{17}},
	{18, []int{18}},
	{19, []int{17}},
	{20, []int{20}},
	{21, []int{22}},
	{22, []int{22}},
	{23, []int{23}},
	{24, []int{24}},
	{25, []int{27}},
	{26, []int{26}},
	{27, []int{27}},
	{28, []int{28}},
	{29, []int{29}},
	{30, []int{35}},
	{31, []int{26}},
	{32, []int{32}},
	{33, []int{33}},
	{34, []int{34}},
	{35, []int{35}},
	{36, []int{34}},
}
