---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/proxy
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.firebolt.io
  resources:
  - fireboltengineclasses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.firebolt.io
  resources:
  - fireboltengineclasses/finalizers
  - fireboltengines/finalizers
  - fireboltinstances/finalizers
  verbs:
  - update
- apiGroups:
  - compute.firebolt.io
  resources:
  - fireboltengineclasses/status
  - fireboltengines/status
  - fireboltinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.firebolt.io
  resources:
  - fireboltengines
  - fireboltinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
