apiVersion: v2
name: firebolt-operator-crds
description: CRDs for the Firebolt Kubernetes Operator
type: application
version: 0.1.38
appVersion: "v2.5.0"
maintainers:
  - name: firebolt-db
keywords:
  - firebolt
  - operator
  - crds
