apiVersion: v2
name: firebolt-operator-crds
description: CRDs for the Firebolt Kubernetes Operator
type: application
version: 0.1.3
appVersion: "v1.9.0"
maintainers:
  - name: firebolt-analytics
keywords:
  - firebolt
  - operator
  - crds
