apiVersion: v2
name: firebolt-operator-crds
description: CRDs for the Firebolt Kubernetes Operator
type: application
version: 0.1.12
appVersion: "v1.13.0"
maintainers:
  - name: firebolt-db
keywords:
  - firebolt
  - operator
  - crds
