apiVersion: v1
kind: Namespace
metadata:
  name: firebolt
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-cluster-test
  namespace: firebolt
data:
  replicas: "3"
  image: "us-east4-docker.pkg.dev/shared-991415466295/firebolt-analytics/firebolt-core"
  tag: "release-4.31.0-pre.0.20251219132726.3032bf8968ff-amd64"
  cpu: "1"
  memory: "2Gi"
  drainCheckInterval: "5s"

