apiVersion: v1
kind: Namespace
metadata:
  name: firebolt
---
apiVersion: compute.firebolt.io/v1alpha1
kind: FireboltEngine
metadata:
  name: engine-test
  namespace: firebolt
spec:
  replicas: 1
  image:
    repository: "ghcr.io/firebolt-db/engine"
    tag: "dev"
  resources:
    cpu: "1"
    memory: "2Gi"
