apiVersion: v1
kind: Namespace
metadata:
  name: firebolt
---
apiVersion: compute.firebolt.io/v1alpha1
kind: FireboltInstance
metadata:
  name: production
  namespace: firebolt
spec:
  metadata: {}
  gateway: {}
