apiVersion: v2
name: firebolt-kubernetes-operator
description: Helm chart for the Firebolt Kubernetes Operator
type: application
version: 0.1.4
appVersion: "v1.2.1"
maintainers:
  - name: firebolt-analytics
keywords:
  - firebolt
  - operator
  - kubernetes
