apiVersion: v2
name: firebolt-kubernetes-operator
description: Helm chart for the Firebolt Kubernetes Operator
type: application
version: 0.1.22
appVersion: "v1.14.0"
maintainers:
  - name: firebolt-db
keywords:
  - firebolt
  - operator
  - kubernetes
