apiVersion: compute.firebolt.io/v1alpha1
kind: FireboltInstance
metadata:
  name: demo2
spec:
  metadata: {}
  gateway: {}
---
apiVersion: compute.firebolt.io/v1alpha1
kind: FireboltEngine
metadata:
  name: analytics
spec:
  instanceRef: demo2
  replicas: 2
  resources:
    cpu: "1"
    memory: "4Gi"
---
apiVersion: compute.firebolt.io/v1alpha1
kind: FireboltEngine
metadata:
  name: ingest
spec:
  instanceRef: demo2
  replicas: 2
  resources:
    cpu: "1"
    memory: "4Gi"
