{{- if not .Values.postgresql.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dedicated-pensieve.fullname" . }}-postgres-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dedicated-pensieve.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.credentials.username }}
  username: {{ .Values.postgresql.credentials.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.credentials.password }}
  password: {{ .Values.postgresql.credentials.password | b64enc | quote }}
  {{- end }}
{{- end }}
