apiVersion: v2
name: kubernetes-operator
description: Helm chart for the Firebolt Kubernetes Operator
type: application
version: 1.0.16
appVersion: "v2.9.0"
maintainers:
  - name: firebolt-db
keywords:
  - firebolt
  - operator
  - kubernetes
