apiVersion: v2
name: kubernetes-operator
description: Helm chart for the Firebolt Kubernetes Operator
type: application
version: 0.1.32
appVersion: "v1.23.0"
maintainers:
  - name: firebolt-db
keywords:
  - firebolt
  - operator
  - kubernetes
