apiVersion: v2
name: firebolt-operator
description: Helm chart for the Firebolt Kubernetes Operator
type: application
version: 0.1.1
appVersion: "v0.3.0"
icon: https://raw.githubusercontent.com/firebolt-db/firebolt-instance-helm/refs/heads/main/static/firebolt.png
home: "https://github.com/firebolt-db/firebolt-kubernetes-operator"
sources: ["https://github.com/firebolt-db/firebolt-kubernetes-operator"]
maintainers:
  - name: firebolt-db
keywords:
  - firebolt
  - operator
  - kubernetes
