{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "firebolt-operator.serviceAccountName" . }}
  labels:
    {{- include "firebolt-operator.labels" . | nindent 4 }}
  {{- if or .Values.extraAnnotations .Values.serviceAccount.annotations }}
  annotations:
    {{- with .Values.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
