{{- if and .Values.serviceMonitor.operator.enabled .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "firebolt-operator.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "firebolt-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "firebolt-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  endpoints:
    - interval: {{ .Values.serviceMonitor.operator.interval }}
      path: /metrics
      port: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
      {{- if .Values.metrics.secure }}
      scheme: https
      {{- with .Values.serviceMonitor.operator.bearerTokenSecret }}
      {{- if .name }}
      authorization:
        type: Bearer
        credentials:
          name: {{ .name }}
          key: {{ default "token" .key }}
      {{- end }}
      {{- end }}
      tlsConfig:
        insecureSkipVerify: true
      {{- end }}
{{- end }}
