{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "firebolt-operator.fullname" . }}-metrics
  labels:
    {{- include "firebolt-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
      port: {{ include "firebolt-operator.portNumber" .Values.metrics.bindAddress }}
      protocol: TCP
      targetPort: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
  selector:
    {{- include "firebolt-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}
