name: Tests

on:
  pull_request:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a  # v2.1.0
        with:
          app_id: ${{ secrets.GH_APP_CI_GITOPS_APP_ID }}
          private_key: ${{ secrets.GH_APP_CI_GITOPS_KEY_PEM }}

      - name: Configure Git for private modules
        run: git config --global url."https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/".insteadOf "https://github.com/"

      - name: Clone the code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test
        env:
          GOPRIVATE: github.com/firebolt-analytics/*
