name: Tests

on:
  pull_request:

permissions: {}

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ secrets.GH_APP_FB_DB_CI_WRITER_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_FB_DB_CI_WRITER_APP_KEY_PEM }}

      - name: Configure Git for private modules
        env:
          GH_APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: git config --global url."https://x-access-token:${GH_APP_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Clone the code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test
        env:
          GOPRIVATE: github.com/firebolt-db/*
